@startuml ""

' hide the spot
hide circle

' avoid problems with angled crows feet
'skinparam linetype ortho

entity "**profiles**" as profiles {
  id : uuid <<PK>> <<generated>>
  --
  name : varchar(300) 
  --
  stars : integer
  --
  priority : boolean
  --
  level : varchar(10)
  --
  has_reference : boolean
  --
  downloaded : boolean
  --
  references_checked : boolean
  --
  tagged_checked : boolean
  --
  sugestions_checked : boolean
}

entity "**categories**" as categories {
  id : uuid <<PK>> <<generated>>
  --
  name : varchar(200)
}

entity "**types**" as types {
  id : uuid <<PK>> <<generated>>
  --
  name : varchar(200)
}

entity "**profiles_categories**" as profiles_categories{
  profile_id : uuid <<FK>>
  --
  category_id : uuid <<FK>>
}

entity "**profiles_types**" as profiles_types {
  profile_id : uuid <<FK>>
  --
  type_id : uuid <<FK>>
}

categories::id "1" -right- "0..n" profiles_categories::category_id
profiles_categories::profile_id "0..n" -right- "1" profiles::id

profiles::id "1" -right- "0..n" profiles_types::profile_id
profiles_types::type_id "0..n" -right- "1" types::id


@enduml
